let ctx,analyser,stream,source,track,processor,silentGain,running=false,paused=false,startTime=0,last=0;
let weighting='A', view='fft',energy=0,energyTime=0,history=[];
let warmupUntil=0, fastE=undefined, slowE=undefined;
let minFast=Infinity,maxFast=-Infinity,minSlow=Infinity,maxSlow=-Infinity;
let latestLevel=NaN, latestRawLevel=NaN;
let sessionStartedAt=null, calibrationSampling=false, calibrationSamples=[], pendingCalibration=null;
const $=id=>document.getElementById(id); const canv=$('spectrum'), hist=$('history');
const CAL_KEY='slm_calibration_v2';
const NOMINAL_OFFSET=100; // Solo referencia digital→SPL estimada cuando no hay calibración externa.
function resize(c){c.width=Math.max(1,c.clientWidth*devicePixelRatio);c.height=Math.max(1,c.clientHeight*devicePixelRatio)}
function weight(f,w){if(w==='Z')return 0; let f2=f*f;if(w==='A'){let ra=(12200**2*f2*f2)/((f2+20.6**2)*Math.sqrt((f2+107.7**2)*(f2+737.9**2))*(f2+12200**2));return 20*Math.log10(ra)+2;}let rc=(12200**2*f2)/((f2+20.6**2)*(f2+12200**2));return 20*Math.log10(rc)+.06}
function getCalibration(){try{return JSON.parse(localStorage.getItem(CAL_KEY)||'null')}catch{return null}}
function currentOffset(){const c=getCalibration();return c&&Number.isFinite(c.offset)?c.offset:NOMINAL_OFFSET}
function updateCalUI(){const c=getCalibration();$('calStatus').textContent=c?'Calibrado':'Estimación automática';$('calStatus').className=c?'ok':'';$('calOffsetLabel').textContent=c?`Corrección: ${c.offset>=0?'+':''}${c.offset.toFixed(1)} dB`:'Sin calibración externa';}
function label(){let p=weighting;let r=$('response').value==='1'?'SLOW':'FAST'; $('unit').textContent=`dB(${p})`; $('instLabel').textContent=`L${p}${$('response').value==='1'?'S':'F'}`;$('leqLabel').textContent=`L${p}eq,T`;$('maxLabel').textContent=`L${p}max`;$('minLabel').textContent=`L${p}min`;$('histLegend').textContent=`dB(${p})`;if($('mobileWeight'))$('mobileWeight').textContent=p;if($('mobileResponse'))$('mobileResponse').textContent=r;$('referenceUnit').textContent=`dB(${p})`}
document.querySelectorAll('.mode button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode button').forEach(x=>x.classList.remove('active'));b.classList.add('active');weighting=b.dataset.w;label();resetStats()});document.querySelectorAll('.view').forEach(b=>b.onclick=()=>{if(!b.dataset.view)return;document.querySelectorAll('.view[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view});$('response').onchange=()=>{label();updateDisplayedStats()};

// Coeficientes IIR obtenidos por transformación bilineal de las curvas analógicas A/C,
// normalizados a 0 dB a 1 kHz. Se elige el banco más cercano a 44.1 o 48 kHz.
const SOS={
  44100:{A:[[0.2555878203785175,0.511175640757035,0.2555878203785175,1,-0.14053608242071078,0.004937597615540203],[1,-2,1,1,-1.884901217428792,0.8864214718161674],[1,-2,1,1,-1.9941388812663283,0.9941474694445309]],C:[[0.21701321570823098,0.43402643141646197,0.21701321570823098,1,-0.14053608242071078,0.004937597615540203],[1,-2,1,1,-1.9941388812663283,0.9941474694445309]]},
  48000:{A:[[0.23418304260356074,0.4683660852071215,0.23418304260356074,1,-0.22455845805977914,0.012606625271546396],[1,-2,1,1,-1.8938704947230707,0.8951597690946617],[1,-2,1,1,-1.9946144559930215,0.9946217070140843]],C:[[0.19789070701987366,0.3957814140397473,0.19789070701987366,1,-0.22455845805977914,0.012606625271546396],[1,-2,1,1,-1.9946144559930215,0.9946217070140843]]}
};
let filters={A:null,C:null};
function makeCascade(kind,fs){const bank=Math.abs(fs-44100)<Math.abs(fs-48000)?44100:48000;return SOS[bank][kind].map(c=>({b0:c[0],b1:c[1],b2:c[2],a1:c[4],a2:c[5],z1:0,z2:0}))}
function runCascade(x,sections){let y=x;for(const s of sections){const o=s.b0*y+s.z1;s.z1=s.b1*y-s.a1*o+s.z2;s.z2=s.b2*y-s.a2*o;y=o}return y}
function processAudio(ev){if(!running||paused)return;const input=ev.inputBuffer.getChannelData(0);let sumA=0,sumC=0,sumZ=0;for(let i=0;i<input.length;i++){const x=input[i];const a=runCascade(x,filters.A),c=runCascade(x,filters.C);sumA+=a*a;sumC+=c*c;sumZ+=x*x}const n=input.length;if(!n)return;const mean={A:sumA/n,C:sumC/n,Z:sumZ/n}[weighting];if(!(mean>0))return;const rawDb=10*Math.log10(mean);const off=currentOffset();const eCal=mean*Math.pow(10,off/10);latestRawLevel=rawDb;latestLevel=10*Math.log10(eCal);
  const dt=n/ctx.sampleRate, now=performance.now();
  // FAST/SLOW se integran en energía (p²), no promediando dB.
  const af=1-Math.exp(-dt/0.125), as=1-Math.exp(-dt/1.0);
  if(!(fastE>0))fastE=eCal; else fastE+=af*(eCal-fastE);
  if(!(slowE>0))slowE=eCal; else slowE+=as*(eCal-slowE);
  if(calibrationSampling&&Number.isFinite(rawDb))calibrationSamples.push(rawDb);
  if(now>=warmupUntil){
    energy+=eCal*dt; energyTime+=dt;
    const lf=10*Math.log10(fastE), ls=10*Math.log10(slowE);
    minFast=Math.min(minFast,lf);maxFast=Math.max(maxFast,lf);minSlow=Math.min(minSlow,ls);maxSlow=Math.max(maxSlow,ls);
  }
}
async function start(){if(!ctx){const requested={echoCancellation:false,noiseSuppression:false,autoGainControl:false,channelCount:1};stream=await navigator.mediaDevices.getUserMedia({audio:requested,video:false});track=stream.getAudioTracks()[0];ctx=new (window.AudioContext||window.webkitAudioContext)();source=ctx.createMediaStreamSource(stream);analyser=ctx.createAnalyser();analyser.fftSize=8192;analyser.smoothingTimeConstant=0;source.connect(analyser);filters.A=makeCascade('A',ctx.sampleRate);filters.C=makeCascade('C',ctx.sampleRate);
    // ScriptProcessor se usa para mantener compatibilidad amplia (incluido Safari/iOS).
    // El procesamiento es temporal; el analyser queda solo para visualización espectral.
    processor=ctx.createScriptProcessor(1024,1,1);silentGain=ctx.createGain();silentGain.gain.value=0;source.connect(processor);processor.connect(silentGain);silentGain.connect(ctx.destination);processor.onaudioprocess=processAudio;renderMicInfo()}
  await ctx.resume();if(!running){startTime=performance.now();last=startTime;running=true;sessionStartedAt=new Date();resetStats(false)}paused=false;$('status').textContent='● MIDIENDO';$('status').style.color='#d6f23d';requestAnimationFrame(loop)}
function resetStats(resetClock=true){energy=0;energyTime=0;history=[];fastE=undefined;slowE=undefined;minFast=Infinity;maxFast=-Infinity;minSlow=Infinity;maxSlow=-Infinity;latestLevel=NaN;latestRawLevel=NaN;warmupUntil=performance.now()+500;if(resetClock){startTime=performance.now();last=startTime;sessionStartedAt=running?new Date():null}$('min').textContent=$('max').textContent=$('leq').textContent='--.-';$('elapsed').textContent='00:00:00'}
$('start').onclick=()=>start().catch(e=>alert('No fue posible acceder al micrófono. Use HTTPS y autorice el permiso.\n'+e.message));$('pause').onclick=()=>{if(!running)return;paused=!paused;$('status').textContent=paused?'● PAUSADO':'● MIDIENDO';if(!paused){last=performance.now();requestAnimationFrame(loop)}};$('reset').onclick=()=>resetStats(true);$('finish').onclick=finishAndSave;
function spectrumLevels(offset=currentOffset()){let arr=new Float32Array(analyser.frequencyBinCount);analyser.getFloatFrequencyData(arr);let sr=ctx.sampleRate, bin=sr/analyser.fftSize;return {arr,sr,bin,off:offset}}
function updateDisplayedStats(){const useSlow=$('response').value==='1';const e=useSlow?slowE:fastE;const v=e>0?10*Math.log10(e):NaN;const mn=useSlow?minSlow:minFast,mx=useSlow?maxSlow:maxFast;const leq=energyTime>0?10*Math.log10(energy/energyTime):NaN;if(Number.isFinite(v)){$('big').textContent=$('inst').textContent=v.toFixed(1);$('bar').style.width=Math.max(0,Math.min(100,(v-20)/110*100))+'%'}$('leq').textContent=Number.isFinite(leq)?leq.toFixed(1):'--.-';$('max').textContent=Number.isFinite(mx)?mx.toFixed(1):'--.-';$('min').textContent=Number.isFinite(mn)?mn.toFixed(1):'--.-'}
function loop(now){if(!running||paused)return;updateDisplayedStats();const useSlow=$('response').value==='1',e=useSlow?slowE:fastE,v=e>0?10*Math.log10(e):NaN;if(Number.isFinite(v)){history.push(v);if(history.length>900)history.shift()}const sec=(performance.now()-startTime)/1000;$('elapsed').textContent=new Date(sec*1000).toISOString().slice(11,19);drawHistory();if(analyser)drawSpectrum(spectrumLevels());requestAnimationFrame(loop)}
function drawHistory(){resize(hist);let g=hist.getContext('2d'),w=hist.width,h=hist.height;g.clearRect(0,0,w,h);g.strokeStyle='#1c3440';g.lineWidth=1;for(let y=0;y<=5;y++){g.beginPath();g.moveTo(0,y*h/5);g.lineTo(w,y*h/5);g.stroke()}if(history.length<2)return;g.strokeStyle='#d6f23d';g.lineWidth=2*devicePixelRatio;g.beginPath();history.forEach((v,i)=>{let x=i/(history.length-1)*w,y=h-(Math.max(20,Math.min(130,v))-20)/110*h;i?g.lineTo(x,y):g.moveTo(x,y)});g.stroke()}
const oct=[31.5,63,125,250,500,1000,2000,4000,8000,16000];const third=[25,31.5,40,50,63,80,100,125,160,200,250,315,400,500,630,800,1000,1250,1600,2000,2500,3150,4000,5000,6300,8000,10000,12500,16000];
function bandLevel(s,fc,frac){let r=2**(1/(2*frac)),lo=fc/r,hi=fc*r,sum=0;for(let i=Math.max(1,Math.floor(lo/s.bin));i<Math.min(s.arr.length,Math.ceil(hi/s.bin));i++){let f=i*s.bin,db=s.arr[i]+s.off+weight(f,weighting);sum+=10**(db/10)}return sum>0?10*Math.log10(sum):20}
function drawSpectrum(s){resize(canv);let g=canv.getContext('2d'),w=canv.width,h=canv.height;g.clearRect(0,0,w,h);if(view==='fft'){g.strokeStyle='#d6f23d';g.lineWidth=1.5*devicePixelRatio;g.beginPath();let started=false;for(let i=1;i<s.arr.length;i++){let f=i*s.bin;if(f<20||f>20000)continue;let x=(Math.log10(f)-Math.log10(20))/(Math.log10(20000)-Math.log10(20))*w,db=s.arr[i]+s.off+weight(f,weighting),y=h-(Math.max(20,Math.min(130,db))-20)/110*h;started?g.lineTo(x,y):g.moveTo(x,y);started=true}g.stroke();$('bands').innerHTML=''}else{let list=view==='oct'?oct:third,frac=view==='oct'?1:3;$('bands').innerHTML=list.map(fc=>{let db=bandLevel(s,fc,frac),ht=Math.max(1,Math.min(100,(db-20)/110*100));return `<div class="band"><i style="height:${ht*1.6}px"></i>${fc>=1000?(fc/1000)+'k':fc}</div>`}).join('')}}
function boolText(v){return v===false?'desactivada':v===true?'activada':'no informado'}
function renderMicInfo(){if(!track)return;const s=track.getSettings?track.getSettings():{};const rows=[['Micrófono',track.label||'Entrada de audio'],['Sample rate',s.sampleRate?`${s.sampleRate} Hz`:(ctx?`${ctx.sampleRate} Hz`:'no informado')],['Canales',s.channelCount??'no informado'],['AGC',boolText(s.autoGainControl)],['Supresión de ruido',boolText(s.noiseSuppression)],['Cancelación de eco',boolText(s.echoCancellation)]];$('micInfo').innerHTML=rows.map(([a,b])=>`<div><span>${a}</span><b>${b}</b></div>`).join('')}
$('openCal').onclick=()=>{$('calibrationPanel').classList.remove('hidden');$('calibrationPanel').scrollIntoView({behavior:'smooth',block:'start'})};$('closeCal').onclick=()=>$('calibrationPanel').classList.add('hidden');$('referenceLevel').oninput=()=>{$('refCalLevel').textContent=(+$('referenceLevel').value||0).toFixed(1);pendingCalibration=null;$('saveCal').disabled=true;$('newCalOffset').textContent='--.-'};
$('sampleCal').onclick=async()=>{try{if(!running)await start();if(paused){paused=false;last=performance.now();requestAnimationFrame(loop)}calibrationSamples=[];calibrationSampling=true;$('sampleCal').disabled=true;$('sampleCal').textContent='Midiendo…';await new Promise(r=>setTimeout(r,3000));calibrationSampling=false;const vals=calibrationSamples.filter(Number.isFinite);if(!vals.length)throw new Error('No se obtuvieron muestras válidas.');const energyMean=vals.reduce((a,v)=>a+10**(v/10),0)/vals.length;const raw=10*Math.log10(energyMean);const ref=+$('referenceLevel').value;if(!Number.isFinite(ref))throw new Error('Ingrese un nivel de referencia válido.');const off=ref-raw;pendingCalibration={offset:off,reference:ref,raw,weighting,createdAt:new Date().toISOString()};$('rawCalLevel').textContent=raw.toFixed(1);$('refCalLevel').textContent=ref.toFixed(1);$('newCalOffset').textContent=`${off>=0?'+':''}${off.toFixed(1)} dB`;$('saveCal').disabled=false}catch(e){alert(e.message)}finally{$('sampleCal').disabled=false;$('sampleCal').textContent='Medir 3 s'}};
$('saveCal').onclick=()=>{if(!pendingCalibration)return;localStorage.setItem(CAL_KEY,JSON.stringify(pendingCalibration));pendingCalibration=null;updateCalUI();$('saveCal').disabled=true;resetStats(true);alert('Calibración guardada en este dispositivo/navegador.')};$('clearCal').onclick=()=>{localStorage.removeItem(CAL_KEY);pendingCalibration=null;updateCalUI();$('rawCalLevel').textContent='--.-';$('newCalOffset').textContent='--.-';$('saveCal').disabled=true;resetStats(true)};
function storedSessions(){try{return JSON.parse(localStorage.getItem('slm_sessions_v1')||'[]')}catch{return []}}
function saveSessions(items){localStorage.setItem('slm_sessions_v1',JSON.stringify(items))}
function fmtDate(iso){return new Intl.DateTimeFormat('es-CL',{dateStyle:'short',timeStyle:'medium'}).format(new Date(iso))}
function fmtDuration(sec){sec=Math.max(0,Math.round(sec));let h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),ss=sec%60;return [h,m,ss].map(x=>String(x).padStart(2,'0')).join(':')}
function finishAndSave(){const useSlow=$('response').value==='1',mn=useSlow?minSlow:minFast,mx=useSlow?maxSlow:maxFast;if(!running||!energyTime||!Number.isFinite(mn)||!Number.isFinite(mx)){alert('Primero inicia una medición válida.');return}const leq=10*Math.log10(energy/energyTime), ended=new Date(),cal=getCalibration();const item={id:Date.now(),startedAt:(sessionStartedAt||ended).toISOString(),endedAt:ended.toISOString(),duration:energyTime,weighting,response:useSlow?'SLOW':'FAST',leq:+leq.toFixed(1),max:+mx.toFixed(1),min:+mn.toFixed(1),calibrated:!!cal,calOffset:currentOffset()};const items=storedSessions();items.unshift(item);saveSessions(items.slice(0,100));running=false;paused=false;$('status').textContent='● GUARDADO';$('status').style.color='#7bd7a6';renderSessions()}
function deleteSession(id){saveSessions(storedSessions().filter(x=>x.id!==id));renderSessions()}
function renderSessions(){const items=storedSessions(), list=$('sessionList'), empty=$('noSessions');if(!list)return;empty.style.display=items.length?'none':'block';list.innerHTML=items.map(x=>{let p=x.weighting;return `<article class="session"><div class="session-head"><div><b>${fmtDate(x.startedAt)}</b><span>${fmtDuration(x.duration)} · ${p} · ${x.response} · ${x.calibrated?'calibrado':'sin calibrar'}</span></div><button class="delete-session" data-id="${x.id}" aria-label="Eliminar medición">Eliminar</button></div><div class="session-values"><div><strong>${x.leq.toFixed(1)}</strong><span>L${p}eq,T · dB(${p})</span></div><div><strong>${x.max.toFixed(1)}</strong><span>L${p}max · dB(${p})</span></div><div><strong>${x.min.toFixed(1)}</strong><span>L${p}min · dB(${p})</span></div></div></article>`}).join('');list.querySelectorAll('.delete-session').forEach(b=>b.onclick=()=>deleteSession(+b.dataset.id))}
$('clearSessions').onclick=()=>{if(storedSessions().length&&confirm('¿Borrar todas las mediciones guardadas en este dispositivo?')){saveSessions([]);renderSessions()}};
label();updateCalUI();renderSessions();resize(hist);resize(canv);
